baseURL = "https://luckylh.github.io/"
languageCode = "en-us"
title = "Frank's Blog Site"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "franks-blog-site"

# Google Analytics UA number
googleAnalytics = "UA-109126169-1"

# Copyright of your post
copyright = "© 本博客所有文章遵循Creative Attribution-Noncommercial-Share Alike Commons（知识共享署名-非商业性使用-相同方式共享 2.5 中国大陆许可协议）"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "所有博客"
  weight = 10
  identifier = "home"
  url = "/"

# Add your own params here
[params]
  author = "Frank Liu"
  avatar = "/img/avatar.jpg"
  seotitle = "Frank's Blog Site"
  subtitle = "从入门到放弃 ╮(￣▽￣)╭"
  description = "15年IT从业经验, 关注区块链, web后端, 数据处理等各项技术."
  paginate = 10

  # Choose your social networks
  email = "luckylh@gmail.com"
  github = "luckylh"
  #twitter = "twitter_username"
  linkedin = "luckylhcn"
  #weibo = "weibo_username"
  wechat= "/img/qrcode.jpg"
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  changyan = false
  changyanId = ""
  changyanConf = ""

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "ZOy_Sdpg2VaZrIpKusALmoUUb0whvSay2fAFzLnSzL4"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "6274A832EC64ADB274005DDB5C56A19A"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  baiduSiteVerification = "OHleGXO2iu"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  sogouSiteVerification = "FVG2B07Ui1"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  soSiteVerification = "2a3ac95a0fc533e6e25e682227f6c5b3"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  baiduTongji = "b59ac07f8233e0a9edde1b795ccdfa43"

  # ICP Number (China Only)
  # ICP = ""
